version = 0.1

[default.deploy.parameters]
stack_name = "ffxiv-finder-ultima"
resolve_s3 = true
s3_prefix = "ffxiv-finder-ultima"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Limit=\"5\" FilterFile=\"data/filter.json\""
image_repositories = []

[default.global.parameters]
region = "ap-northeast-1"
