version = 0.1

[default.deploy.parameters]
stack_name = "ffxiv-finder-ultima"
resolve_s3 = true
s3_prefix = "ffxiv-finder-ultima"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Query=\"絶アルテマ\" Limit=\"5\""
image_repositories = []

[default.global.parameters]
region = "ap-northeast-1"
